//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.WorkUser = new HashSet<WorkUser>();
        }
    
        public int Code { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public Nullable<int> WorkExperienceID { get; set; }
        public string Profession { get; set; }
        public string Salary { get; set; }
        public string Schedule { get; set; }
    
        public virtual WorkExperience WorkExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkUser> WorkUser { get; set; }
    }
}
